site_name: PersistenceMap

repo_url: https://github.com/PersistenceMap/PersistenceMap

pages:
- Introduction: index.md

- SQL:
    - Create a Context: sql/context.md
    - Code First: sql/create-database.md
    - Create Tables: common/create-table.md
    - Reading Data: common/select.md
    - Stored Procedure: sql/storedprocedures.md
    - Diagnostics: common/diagnostics.md

- SQLite:
    - Create a Context: sqlite/context.md
    - Code First: sqlite/create-database.md
    - Create Tables: common/create-table.md
    - Diagnostics: common/diagnostics.md

theme: mkdocs